{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "node-exporter.labels" . | nindent 4 }}
{{- end }}
