apiVersion: v1
appVersion: 13.11.4
description: Gitlab operator for managing upgrades
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
keywords:
- gitlab
- operator
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: operator
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/operator
- https://gitlab.com/gitlab-org/charts/components/gitlab-operator
version: 4.11.4
