cat > prometheus-svc-nodeport.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc-nodeport
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: web
      port: 9090
      targetPort: http
      nodePort: 33501
EOF