version: "3"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ./standalone-logs/:/home/nacos/logs
    - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    network_mode: bridge
    ports:
    - "8850:8848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    volumes:
    - ./promethues/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: bridge
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: bridge
    ports:
      - 3000:3000
    restart: on-failure