version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "9001:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/filebrower:/srv"
    networks:
      - "yfgj_net"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=yfgj_nat"
        - "traefik.http.routers.filebrowser.rule=Host(`file.ctq6.cn`)"
        - "traefik.http.services.filebrowser_filebrowser.loadbalancer.server.port=80"
        - "traefik.http.routers.filebrowser.tls=true"
        - "traefik.http.routers.filebrowser.tls.certresolver=foo"
        - "traefik.http.routers.filebrowser.tls.domains[0].main=ctq6.cn"
        - "traefik.http.routers.filebrowser.tls.domains[0].sans=*.ctq6.cn"
        - "traefik.http.routers.filebrowser.middlewares=redirect-https"
        - "traefik.http.routers.filebrowser.entrypoints=websecure"
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  yfgj_net:
    external: true
    name: yfgj_net