version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "9001:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/filebrower:/srv"
    networks:
      - "traefik-public"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.filebrowser.rule=Host(`file.local.cluster`)"
        - "traefik.http.routers.filebrowser.entrypoints=websecure"
        - "traefik.http.routers.filebrowser.tls=true"
        - "traefik.http.routers.filebrowser.tls.certresolver=foo"
        - "traefik.http.routers.filebrowser.tls.domains[0].main=local.cluster"
        - "traefik.http.routers.filebrowser.tls.domains[0].sans=*.local.cluster" 
        - "traefik.http.services.filebrowser.loadbalancer.server.port=9001"
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
<<<<<<< HEAD
  yfgj_net:
    external: true
    name: yfgj_net
=======
  traefik-public:
    external: true
>>>>>>> 8f46ec4b05c9e99f1d8e7aae50c2e52cf737a2da
