version: "3.8"

services:
  busybox:
    image: busybox
    networks:
      - swarm_net
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  swarm_net:
    external: true
    name: swarm_net