version: "3.8"

secrets:
  aliyun_region_id:
    file: "/root/ssl/aliyun_region_id"
  aliyun_access_key:
    file: "/root/ssl/aliyun_access_key"
  aliyun_secret_key:
    file: "/root/ssl/aliyun_secret_key"

services:
  traefik:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--accesslog=true"
      - "--log=true"
      - "--log.filepath=/tmp/traefik.err.log"
      - "--accesslog.filepath=/tmp/traefik.access.log"
      - "--providers.docker.network=yfgj_net"
      - "--certificatesresolvers.foo.acme.dnschallenge=true"
      - "--certificatesresolvers.foo.acme.dnschallenge.provider=alidns"
      - "--certificatesresolvers.foo.acme.dnschallenge.resolvers=114.114.114.114:53,8.8.8.8:53"
      - "--certificatesresolvers.foo.acme.keytype=EC256" #RSA4096
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.foo.acme.email=plyx_46204@126.com"
      - "--certificatesresolvers.foo.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    secrets:
      - "aliyun_region_id"
      - "aliyun_access_key"
      - "aliyun_secret_key"
    environment:
      - "ALICLOUD_REGION_ID_FILE=/run/secrets/aliyun_region_id"
      - "ALICLOUD_ACCESS_KEY_FILE=/run/secrets/aliyun_access_key"
      - "ALICLOUD_SECRET_KEY_FILE=/run/secrets/aliyun_secret_key"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/letsencrypt:/letsencrypt"
    networks:
      - "yafgj_net"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  yfgj_net:
    external: true
    name: yfgj_net