version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - "yfgj_compose"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    hostname: kafka-server
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      yfgj_compose:
        ipv4_address: "192.168.1.10"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://192.168.1.10:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://120.79.77.84:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  yfgj_compose:
    external: true