version: "3.8"

services:
  nginx:
    image: nginx:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 8088:80
    networks:
      - yfgj_net
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=yfgj_net"
        - "traefik.http.routers.nginx-dashboard.rule=Host(`nginx.ctq6.cn`) && Path(`/`)"
        - "traefik.http.services.nginx_nginx.loadbalancer.server.port=80"
        - "traefik.http.routers.nginx-dashboard.entrypoints=web"
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  yfgj_net:
    external: true
    name: yfgj_net

