version: "3.9"

services:
  redis:
    image: idoop/zentao:latest
    networks:
      yfgj_net:
        ipv4_address: 10.0.16.2
    ports:
      - 9000:80
      - 9001:3306
    envrionment:
      - ADMINER_USER="root"
      - ADMINER_PASSWD="123456"
      - BIND_ADDRESS="false"
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    volumes:
      - /data/zbox:/opt/zbox
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: '0.50'
      #     memory: 50M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  yfgj_net:
    external: true
    name: yfgj_net