version: "3.8"


secrets:
  smtppasswd:
    external: true

services:
  bitwarden:
    image: bitwardenrs/server:latest
    #image: vaultwarden/server:latest
    ports:
      - "9002:80"
      - "9003:3012"
    secrets:
      - "smtppasswd"
    environment:
      #- "SMTP_PASSWORD_FILE=/run/secrets/smtppasswd"
      #- "SMTP_HOST="
      #- "SMTP_FROM="
      #- "SMTP_PORT"
      #- "SMTP_SSL=true"
      #- "SMTP_USERNAME="
      #- "SIGNUPS_ALLOWED=false"
      - "WEBSOCKET_ENABLED=true"
      - "LOG_FILE=/data/bitwarden.log"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/bitwarden:/data"
    networks:
      - "yfgj_net"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=yfgj_nat"
        #- "traefik.http.routers.bitwarden.rule=Host(`bitwarden.ctq6.cn`) && Path(`/notifications/hub`)"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.ctq6.cn`)"
        - "traefik.http.services.bitwarden_bitwarden.loadbalancer.server.port=80"
        - "traefik.http.routers.bitwarden.tls=true"
        - "traefik.http.routers.bitwarden.tls.certresolver=foo"
        - "traefik.http.routers.bitwarden.tls.domains[0].main=ctq6.cn"
        - "traefik.http.routers.bitwarden.tls.domains[0].sans=*.ctq6.cn"
        - "traefik.http.routers.bitwarden.middlewares=redirect-https"
        - "traefik.http.routers.bitwarden.entrypoints=websecure"
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  yfgj_net:
    external: true
    name: yfgj_net