{
 "title": "Traefik 1.6+ - Updated",
 "description": "Traefik dashboard prometheus Updated version for use with treafik 1.6+",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "service", "query": "label_values(protocol)" },
   { "name": "entrypoints", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "$service return code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total{entrypoint=~\"we|websecure\",namespace!=\"kube-system\",group=\"pre-cent\"}) by (method, code, entrypoint)",
     "legendFormat": "pre 中心地域　{{method}} : {{code}}: {{entrypoint}}"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{entrypoint=~\"we|websecure\",namespace!=\"kube-system\",group=\"dist-sz-pre\"}) by (method, code, entrypoint)",
     "legendFormat": "pre 分布地域　{{method}} : {{code}}: {{entrypoint}}"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{entrypoint=~\"we|websecure\",namespace!=\"kube-system\",group=\"prod-cent\"}) by (method, code, entrypoint)",
     "legendFormat": "prod 中心地域　{{method}} : {{code}}: {{entrypoint}}"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{entrypoint=~\"we|websecure\",namespace!=\"kube-system\",group=\"prod-dist-sz\"}) by (method, code, entrypoint)",
     "legendFormat": "prod 分布地域　{{method}} : {{code}}: {{entrypoint}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(traefik_entrypoint_request_duration_seconds_sum) + sum(traefik_service_request_duration_seconds_sum)) / (sum(traefik_entrypoint_requests_total)  + sum(traefik_service_requests_total)) * 1000"
    }
   ]
  },
  {
   "title": "Requests over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total-(traefik_entrypoint_requests_total{group=\"pre-cent\"} offset 5m))",
     "legendFormat": "pre 中心地域　Tota requests"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total-(traefik_entrypoint_requests_total{group=\"dist-sz-pre\"} offset 5m))",
     "legendFormat": "pre 分布地域　Total Requests"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total-(traefik_entrypoint_requests_total{group=\"prod-cent\"} offset 5m))",
     "legendFormat": "prod 中心地域　Total Requests"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total-(traefik_entrypoint_requests_total{group=\"prod-dist-sz\"} offset 5m))",
     "legendFormat": "prod 分布地域　Total Requests"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"pre-cent\"} - (traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"pre-cent\"} offset 5m)",
     "legendFormat": "pre 中心地域　{{method}} : {{code}}  {{entrypoint}} "
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"dist-sz-pre\"} - (traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"dist-sz-pre\"} offset 5m)",
     "legendFormat": "pre 分布地域　{{method}} : {{code}}  {{entrypoint}} "
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"prod-cent\"} - (traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"prod-cent\"} offset 5m)",
     "legendFormat": "prod 中心地域　{{method}} : {{code}}  {{entrypoint}} "
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"prod-dist-sz\"} - (traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\",group=\"prod-dist-sz\"} offset 5m)",
     "legendFormat": "prod 分布地域　{{method}} : {{code}}  {{entrypoint}} "
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"pre-cent\"}- (traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"pre-cent\"} offset 5m)",
     "legendFormat": "pre 中心地域　{{ method }} : {{code}} : {{ service}}"
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"dist-sz-pre\"}- (traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"dist-sz-pre\"} offset 5m)",
     "legendFormat": "pre 分布地域　{{ method }} : {{code}} : {{ service}}"
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"prod-cent\"}- (traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"prod-cent\"} offset 5m)",
     "legendFormat": "prod 中心地域　{{ method }} : {{code}} : {{ service}}"
    },
    {
     "expr": "traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"prod-dist-sz\"}- (traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\",group=\"prod-dist-sz\"} offset 5m)",
     "legendFormat": "prod 分布地域　{{ method }} : {{code}} : {{ service}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_service_requests_total{group=\"pre-cent\"} ",
     "legendFormat": "pre 中心地域　{{ service }}  {{method}} {{ code}}"
    },
    {
     "expr": "traefik_service_requests_total{group=\"dist-sz-pre\"} ",
     "legendFormat": "pre 分布地域　{{ service }}  {{method}} {{ code}}"
    },
    {
     "expr": "traefik_service_requests_total{group=\"prod-cent\"}",
     "legendFormat": "prod 中心地域　{{ service }}  {{method}} {{ code}}"
    },
    {
     "expr": "traefik_service_requests_total{group=\"prod-dist-sz\"}",
     "legendFormat": "prod 分布地域　{{ service }}  {{method}} {{ code}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total{protocol =~ \"http|https\",entrypoint=~\"web|websecure\",group=\"dist-sz-pre\"})",
     "legendFormat": "pre  分布地域"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{protocol =~ \"http|https\",entrypoint=~\"web|websecure\",group=\"pre-cent\"})",
     "legendFormat": "pre 中心地域　"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{protocol =~ \"http|https\",entrypoint=~\"web|websecure\",group=\"prod-cent\"})",
     "legendFormat": "prod 中心地域"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{protocol =~ \"http|https\",entrypoint=~\"web|websecure\",group=\"prod-dist-sz\"})",
     "legendFormat": "prod 分布地域"
    }
   ]
  }
 ]
}