# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'alertmanager'

    static_conifgs:
    - targets:
      - 'localhost:9093'

  - job_name: 'node-export'
    
    static_configs:
    - targets:
      - 'rabbitmq-node01:9100'
      - 'rabbitmq-node02:9100'
      - 'rabbitmq-node03:9100'
      - '172.16.0.7:9100'
      - '172.16.0.16:9100'
      - '172.16.0.13:9100'
      - '172.16.0.5:9100'

  - job_name: 'grafana'
    
    static_configs:
    - targets:
      - 'rabbitmq-node03:3000'

  - job_name: 'rabbitmq'
    
    static_configs:
    - targets:
      - 'rabbitmq-node01:15692'
      - 'rabbitmq-node02:15692'
      - 'rabbitmq-node03:15692'

  - job_name: 'cadvisor'

    static_configs:
    - targets:
      - '172.16.0.7:8080'
      - '172.16.0.16:8080'
      - '172.16.0.13:8080'
      - '172.16.0.5:8080'