apiVersion: v1
kind: PersistentVolume
metadata: 
  name: k8s-pv-zk1
  namespace: bigdata
  labels: 
    type: local
spec: 
  capacity: 
    storage: 2Gi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/pv/zk1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk2
  namespace: bigdata
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv/zk2
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk3
  namespace: bigdata
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv/zk3
  persistentVolumeReclaimPolicy: Recycle