version: "3.8"

# secrets:
#   influxdb_pwd:
#     #external: true
#     file: "/root/.secret/influxdb_pwd"
services:
  loki:
    image: grafana/promtail
    # environment:
    networks:
      - yfgj_net
      #- /data/influxdb/config.yml:/etc/influxdb2/config.yml
    # secrets:
    #   - influxdb_pwd 
    volumes:
      - /data/promtail/logs:/var/logs
      - /data/promtail/config:/etc/promtail/config
      - /data/logs:/logs
    command: --config.file=/etc/promtail/config/promtail-config.yaml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=yfgj_net"
        - "traefik.http.services.promtail_promtail.loadbalancer.server.port=3100"
        # http 80
        # - "traefik.http.routers.traefik-ui-80.rule=Host(`traefik.ctq6.cn`)" 
        # - "traefik.http.routers.traefik-ui-80.entrypoints=web"
        # http 8443
        #- "traefik.http.routers.traefik-ui-8443.rule=Host(`traefik-8443.ctq6.cn`)" 
        #- "traefik.http.routers.traefik-ui-8443.entrypoints=webnossl"
        # https 443
        - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
        - "traefik.http.routers.promtail.rule=Host(`grafana.ctq6.cn`)"
        - "traefik.http.routers.promtail.tls=true"
        - "traefik.http.routers.promtail.tls.certresolver=foo"
        - "traefik.http.routers.promtail.tls.domains[0].main=ctq6.cn"
        - "traefik.http.routers.promtail.tls.domains[0].sans=*.ctq6.cn"
        - "traefik.http.routers.promtail.entrypoints=websecure"
        - "traefik.http.routers.promtail.middlewares=redirect-https"
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  yfgj_net:
    external: true
    name: yfgj_net