dev:
    aliyun:
        access-key-id : 
        access-key-secret : 
        region-id : 
    nacos:
        server_addr: 
        namespace: 
    jenkins:
        secret : 
        dingtalk_url : 
        jenkins_url : 
        user_id : 
        api_token : 
        dev:
            view_name: 
            job_name : 
        test:
            view_name: 
test:
    aliyun:
        access-key-id : 
        access-key-secret : 
        region-id : 
    nacos:
        server_addr: 
        namespace: 
    jenkins:
        secret : 
        dingtalk_url : 
        jenkins_url : 
        user_id : 
        api_token : 
        dev:
            view_name: 
            job_name : 
        test:
            view_name: 
prod:
    aliyun:
        access-key-id : ""
        access-key-secret : ""
        region-id : ""
    nacos:
        server_addr: ""
        namespace: ""
    jenkins:
        secret : 
        dingtalk_url : 
        jenkins_url : 
        user_id : 
        api_token : 
        dev:
            view_name: 
            job_name : 
        test:
            view_name: 
        scrm_gituser: 
        scrm_gituser_token: 

